### PR TITLE
Playground should be triggered to create Services and then Pods once the model is created

### LINKED ISSUE #92: Playground will not reconcile once model created
**What happened**:

Let's image there's no Model in the cluster, I created a Playground, because no Model exists, inference Pods will not be created. However, if I created the corresponding Model, the Playground should be triggered to create Services and then Pods. Right now, this is not true.

The solution is quite simple, make Playground watch for model creation events.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:

- Kubernetes version (use `kubectl version`):
- LWS version:
- llmaz version (use `git describe --tags --dirty --always`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by carlory**
#### What this PR does / why we need it

Let's image there's no Model in the cluster, I created a Playground, because no Model exists, inference Pods will not be created. However, if I created the corresponding Model, the Playground should be triggered to create Services and then Pods. Right now, this is not true.

The solution is quite simple, make Playground watch for model creation events.

#### Which issue(s) this PR fixes

Fixes #92

#### Does this PR introduce a user-facing change?

```release-note
Fix playground should be triggered to create Services and then Pods once the model is created
```

### CODE REVIEW

File: pkg/controller/inference/playground_controller.go [hunk 1]
```diff
@@ -119,6 +119,34 @@ func (r *PlaygroundReconciler) Reconcile(ctx context.Context, req ctrl.Request)
...
+				})
+			}
+			// TODO: handle MultiModelsClaims in the future.
+		}
+		return reqs
+	}
+
 	return ctrl.NewControllerManagedBy(mgr).
 		For(&inferenceapi.Playground{}).
 		Watches(&inferenceapi.Service{}, &handler.EnqueueRequestForObject{},
```
Comment (kerthcet) [inline pkg/controller/inference/playground_controller.go:152]: I guess this can be simplified by 
```
			builder.WithPredicates(predicate.Funcs{
				CreateFunc: func(e event.CreateEvent) bool {
					return true
				},
                        }
```

This is enough I think. By the way, we need an integration test.

Comment (carlory) [reply pkg/controller/inference/playground_controller.go:152]: If a function is nil,  the object will always be added into the queue

```go
// Update implements Predicate.
func (p TypedFuncs[T]) Update(e event.TypedUpdateEvent[T]) bool {
	if p.UpdateFunc != nil {
		return p.UpdateFunc(e)
	}
	return true
}

```

>  By the way, we need an integration test.

will do

File: test/integration/controller/inference/playground_test.go [hunk 2]
```diff
@@ -155,5 +157,53 @@ var _ = ginkgo.Describe("playground controller test", func() {
...
+								return err
+							}
+							return fmt.Errorf("model %s/%s still exists", model.Namespace, model.Name)
+						}, util.IntegrationTimeout, util.Interval).Should(gomega.Succeed())
+
+						gomega.Expect(k8sClient.Create(ctx, playground)).To(gomega.Succeed())
+					},
+					checkPlayground: func(ctx context.Context, k8sClient client.Client, playground *inferenceapi.Playground) {
+						validation.ValidatePlayground(ctx, k8sClient, playground)
+						gomega.Consistently(func() error {
```
Comment (carlory) [inline test/integration/controller/inference/playground_test.go:185]: I'm not sure if no condition is expected.

File: pkg/controller/inference/playground_controller.go [hunk 3]
```diff
@@ -119,6 +119,34 @@ func (r *PlaygroundReconciler) Reconcile(ctx context.Context, req ctrl.Request)
 
 // SetupWithManager sets up the controller with the Manager.
 func (r *PlaygroundReconciler) SetupWithManager(mgr ctrl.Manager) error {
+	mapFn := func(ctx context.Context, obj client.Object) []ctrl.Request {
```
[the remark this answers is not in the document]
Comment (kerthcet) [reply pkg/controller/inference/playground_controller.go:122]: #111 merged

File: test/integration/controller/inference/playground_test.go (hunk 2 above)
Comment (carlory) [reply test/integration/controller/inference/playground_test.go:184]: > n the follow up if you're interested or together with this PR, whatever you like.

I will do it in another PR.

File: pkg/controller/inference/playground_controller.go [hunk 4]
```diff
@@ -119,6 +119,34 @@ func (r *PlaygroundReconciler) Reconcile(ctx context.Context, req ctrl.Request)
...
+		logger := log.FromContext(ctx)
+
+		namespace := obj.GetNamespace()
```
Comment (kerthcet) [inline pkg/controller/inference/playground_controller.go:125]: openModel is a cluster-scope obj, so let's remove this.

**Review by kerthcet — COMMENTED** [review]
Generally LGTM
